language: objective-c
osx_image: xcode8.3
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=Waffle.xcodeproj
git:
  submodules: false
before_script:
  - git submodule update --init --recursive
script:
  - set -o pipefail
  - open -b com.apple.iphonesimulator # Workaround https://github.com/travis-ci/travis-ci/issues/3040
  - xcodebuild clean test -project "Waffle.xcodeproj" -scheme "Waffle" -destination "platform=iOS Simulator,name=iPhone 6 Plus,OS=latest" -configuration Release -enableCodeCoverage YES ENABLE_TESTABILITY=YES | xcpretty
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: never
